export const Icons = {
    ArrowUp: "arrow-up-solid",
    Bars: "bars-solid",
    Bars_Light: "bars-solid-light",
    Check: "check-circle-solid",
    Moon: "moon-solid",
    Sun: "sun-solid",
    Search: "search-solid",
    Times: "times-solid",
    Times_Nav: "close-navigation",
    Times_Nav_Light: "close-navigation-light",
    CV: "cv",
    CV_Light: "cv-light",
    GitHub: "github-brands-solid",
    GitHub_Light: "github-brands-solid-light",
    LinkedIn: "linkedin-in-brands-solid",
    LinkedIn_Light: "linkedin-in-brands-solid-light",
}