name: Build

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20'        # Set the Node.js version
  DOTNET_VERSION: '8.0.x'    # Set the .NET version

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Build frontend using Gulp
        run: gulp
        working-directory: ./Frontend

      # Backend build
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: dotnet restore ./Backend/src/Web.csproj

      - name: Build
        working-directory: ./Backend/src
        run: dotnet build
